#!/bin/sh

. /etc/functions.sh

[ -f "/usr/share/commotion/files/splash.html" ] && { \
mv -f /usr/share/commotion/files/splash.html /etc/nodogsplash/htdocs/splash.html
}

#setup ucitrack
[ -z $(uci_get ucitrack @nodogsplash[0]) ] && { \
  uci_add ucitrack nodogsplash
}
[ -z $(uci_get ucitrack @nodogsplash[0] init) ] && { \
  uci_set ucitrack @nodogsplash[0] init ucidog
  uci add_list ucitrack.@setup_wizard[0].affects=nodogsplash
  uci_commit ucitrack
}

exit 0
