#!/bin/sh

SID=$(uci get applications.settings.sid)
if [ -z "$SID" ]; then
  SID=$(SERVALINSTANCE_PATH=/etc/serval serval-client keyring list |grep -o "^[A-Z0-9]\{64\}")
  if [ -n "$SID" -a -e /etc/config/applications ]; then
    uci set applications.settings.sid=$SID
    uci commit applications
  fi
fi
