#!/bin/sh

[ -f "/usr/share/commotion/files/node-mini.gif" ] && { \
cp -f /usr/share/commotion/files/node-mini.gif /www/luci-static/resources/olsr-viz/node-mini.gif
}

[ -f "/usr/share/commotion/files/node-hna-mini.gif" ] && { \
cp -f /usr/share/commotion/files/node-hna-mini.gif /www/luci-static/resources/olsr-viz/node-hna-mini.gif
}

[ -f "/usr/share/commotion/files/olsr-viz.sh" ] && { \
cp -f /usr/share/commotion/files/olsr-viz.sh /www/cgi-bin/olsr-viz.sh
}

[ -f "/usr/bin/patch" ] && { \
  cd /usr/lib/lua/luci/model/cbi/admin_network/
  patch -p0 < /usr/share/commotion/patches/wifi.lua.patch
}

rm -f /tmp/luci-indexcache

exit 0
