#!/bin/sh

. /etc/functions.sh
#set up all interfaces needed for the setup wizard process
config_load wireless
uci_add wireless wifi-iface commotionAP
uci_set wireless commotionAP mode ap
uci_set wireless commotionAP network client
uci_add wireless wifi-iface commotionMesh
uci_set wireless commotionMesh mode adhoc
uci_commit wireless

exit 0
