#!/bin/sh

. /etc/functions.sh

config_load serval
uci_add serval settings settings
uci_set serval settings enabled false
uci_set serval settings primary_keyring /etc/serval/serval.keyring
uci_set serval settings olsrd_mdp_keyring /etc/commotion/keys.d/mdp/serval.keyring
uci_set serval settings update_primary_keyring false
uci_set serval settings update_mdp_keyring false
uci_set serval settings new_mdp_keyring false
uci_commit serval
/etc/init.d/serval enable

exit 0
