#!/bin/sh /etc/rc.common

#simple script to set hostname in the system when it is applied in UCI

. $IPKG_INSTROOT/lib/config/uci.sh

START=19
STOP=91

reload() {
	local host_name=$(uci_get system @system[0] hostname)
	len=${#host_name}
	if [[ "$len" -gt 0 ]]; then
		echo $host_name > /proc/sys/kernel/hostname
	fi
	
	return 0
}
