#!/bin/sh /etc/rc.common
# UCI file to allow basic serval modifications through LuCI with proper UI feel 

. /lib/functions/commotion.sh
. /lib/config/uci.sh

START=19
STOP=91

reload() {
	#core vars
	local enabled=$(uci_get serval settings enabled)
	local upload=cbid.serval.settings._upload

	#mpd vars
	local mdp_sid=$(uci_get serval settings mdp_sid)
	local update_mdp=$(uci_get serval settings update_mdp_keyring)
	local mdp_keyring=$(uci_get serval settings olsrd_mdp_keyring)
	local new_mdp=$(uci_get serval settings new_mdp_keyring)

	#primary key vars
	local update_primary=$(uci_get serval settings update_primary_keyring)
	local primary_keyring=$(uci_get serval settings primary_keyring)
	
	if [ "$enabled" == "true" ]; then
		uci_add "olsrd" "LoadPlugin" "olsrd-mdp"
		uci_set "olsrd" $CONFIG_SECTION "library" "olsrd_mdp.so.0.1"
		uci_set "olsrd" $CONFIG_SECTION "servalpath" $mdp_keyring
		uci_set "olsrd" $CONFIG_SECTION "sid" $mdp_sid
	else
		uci_remove "olsrd" "olsrd-mdp"
	fi
	if [ "$update_mdp" == "true" ]; then
	   	 mv /lib/uci/upload/$upload $mdp_keyring/serval.keyring || return 1
	   	 export SERVALINSTANCE_PATH=$mdp_keyring
	   	 serval-client stop && sleep 1
	   	 serval-client start || return 1
		 uci_set "olsrd" "olsrd-mdp" "sid" $mdp_sid
		 uci_set "olsrd" "olsrd-mdp" "servalpath" $mdp_keyring
	elif [ -e "/lib/uci/upload/$upload" ]; then
		rm /lib/uci/upload/$upload
	fi
	uci_set serval settings update_mdp_keyring 'false'
	if [ "$update_primary" == "true" ]; then
	   mv /lib/uci/upload/$upload $primary_keyring/serval.keyring || return 1
	   #restart servald to have settings restart
	   export SERVALINSTANCE_PATH=$primary_keyring
	   serval-client stop && sleep 1
	   serval-client start
	elif [ -e "/lib/uci/upload/$upload" ]; then
		rm /lib/uci/upload/$upload
	fi
	if [ "$new_mdp" == "true" ]; then
	   #delete old key
	   rm $mdp_keyring/serval.keyring || return 1
	   #have serval make a new key
	   export SERVALINSTANCE_PATH=$mdp_keyring
	   serval-client stop && sleep 1
	   new_sid=serval-client start
	   #get sid from serval
	   #new_mdp_sid=????????????
	   uci_set "olsrd" "mdpplugin" "sid" $new_sid
	   uci_set "olsrd" "mdpplugin" "servalpath" $mdp_keyring
	fi
	uci_set serval settings new_mdp_keyring 'false'
	uci_commit serval
	uci_commit olsrd
}
