#!/bin/sh /etc/rc.common

#simple barely functional nodogsplash uci-track script to set nodogsplash uci values that were set.

. /lib/functions/commotion.sh
. /lib/config/uci.sh

START=19
STOP=91

reload() {
	#nodogsplash configuration file.
	local conffile=/etc/nodogsplash/nodogsplash.conf
	#disable/enable nodogsplash
	local enable=$(uci_get nodogsplash settings enable)
	if [ "$enable" == '1' ]; then #this might come back as a string and not as a intiger. Check and fix that.
		/etc/init.d/nodogsplash disable  || return 0
	else
		/etc/init.d/nodogsplash enable  || return 0
	fi
	
	#convert splash page time into minues
	local splash_time=$(uci_get nodogsplash settings splashtime)
	local splash_unit=$(uci_get nodogsplash settings splashunit)
	if [ "$splash_unit" == "days" ]; then
		splash_time=$(($splash_time*60))
	elif [ "$splash_unit" == "hours" ]; then
		splash_time=$(($splash_time*24*60))
	elif [ "$splash_unit" == "seconds" ]; then
		splash_time=$(($splash_time/60))
	fi
	#set splashpage time
	sed -i "s/^\(ClientIdleTimeout \).*/\1  $splash_time/" $conffile ||  return 0
	sed -i "s/^\(ClientForceTimeout \).*/\1 $splash_time/" $conffile || return 0
	
	#get and set interface name
	local interface=$(uci_get nodogsplash interfaces interface)
	local network=$(uci_get wireless $interface network)
	sed -i "s/^\(GatewayInterface \).*/\1 $interface/" $conffile || return 0
	/etc/init.d/nodogsplash stop && sleep 1
	/etc/init.d/nodogsplash start
}
